# Generated by Django 5.2.1 on 2025-05-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_delete_blogpost_alter_project_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
